gantry_robot_manipulator:
  kinematics_solver: eth_rfl_fixed-xz_gantry_robot_manipulator_kinematics/IKFastKinematicsPlugin
  kinematics_solver_attempts: 3
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
